image:
  repository: wdxxsez/helmi
  tag: "1.0.1"
  pullPolicy: Always

replicaCount: 1

serviceType: ClusterIP

helmi:
  url: http://helmi-service-broker.k8s.io
  username: admin
  password: helmi
  namespace: kube-system
  tillerhost: ""
  repos:
  - name: https://kubernetes-charts.storage.googleapis.com
    url: stable
  - name: monostream
    url: http://monostream-helm.s3-eu-west-1.amazonaws.com/charts

ingress:
  hosts:
  - helmi-service-broker.k8s.io
  # annotations:
  #   kubernetes.io/tls-acme: "true"
  #   ingress.kubernetes.io/secure-backends: "true"
  # tls:
  # - secretName: helmi-tls-secret
  # cert: |
  # key: |

kubeconfig:
  server: https://192.168.213.131:6443
  cluster: kubernetes
  username: helmi@k8s.io  # the username must bind the cluster-admin role
  currentContext: helmi
  userSet:
    # token: xxxx
    auth-provider:
      name: oidc
      config:
        client-id: kubernetes
        client-secret: k8s-changeme
        idp-certificate-authority: /app/tls/ca.pem
        idp-issuer-url: https://uaa.k8s.io/oauth/token
        id-token:
        refresh-token:

tls:
  cacert: |

service_config:
  loglevel: DEBUG
  allow_user_provision_parameters: true
  allow_user_update_parameters: true
  allow_user_bind_parameters: true
  services:
    mariadb:
      chart: stable/mariadb
      chart_version: 1.0.7
    minio:
      chart: stable/minio
      chart_version: 0.3.0
    rabbitmq:
      chart: stable/rabbitmq
      chart_version: 0.6.8
    mongodb:
      chart: stable/mongodb
      chart_version: 0.4.9
    redis:
      chart: stable/redis
      chart_version: 0.9.0
    cassandra:
      chart: monostream/cassandra
      chart_version: 0.2.7
    muescheli:
      chart: monostream/muescheli
      chart_version: 0.1.5