---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-mysql
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-mysql
    spec:
      containers:
      - name: spring-mysql
        image: wdxxsez/spring-music-mysql:1.0
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_DB_HOST
          valueFrom:
            secretKeyRef:
              name: springmusic-mariadb-credentials
              key: hostname
        - name: MYSQL_DB_PORT
          valueFrom:
            secretKeyRef:
              name: springmusic-mariadb-credentials
              key: port
        - name: MYSQL_DB_USER
          valueFrom:
            secretKeyRef:
              name: springmusic-mariadb-credentials
              key: username
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: springmusic-mariadb-credentials
              key: password
        - name: MYSQL_DB_NAME
          valueFrom:
            secretKeyRef:
              name: springmusic-mariadb-credentials
              key: database
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    name: spring-mysql
    http-route-sync: spring-mysql
  name: spring-mysql
  annotations:
    traefik.backend.loadbalancer.method: drr
spec:
  ports:
    - port: 8080
  selector:
    app: spring-mysql
  type: NodePort