apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: mariadb-service-instance
  namespace: default
spec:
  clusterServiceClassExternalName: mariadb
  clusterServicePlanExternalName: free
  parameters:
    serviceType: NodePort