apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-catalog
data:
  catalog.yaml:
{{ toYaml .Values.service_config | indent 4 }}
  kubeconfig.yaml:
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        certificate-authority: "/app/tls/ca.pem"
        server: {{ .Values.kubeconfig.server }}
      name: kubernetes
    contexts:
    - context:
        cluster: {{ .Values.kubeconfig.cluster }}
        user: {{ .Values.kubeconfig.username }}
      name: {{ .Values.kubeconfig.currentContext }}
    current-context: {{ .Values.kubeconfig.currentContext }}
    users:
    - name: {{ .Values.kubeconfig.username }}
      user:
{{ toYaml .Values.kubeconfig.userSet | indent 8 }}
