apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "fullname" . }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ template "fullname" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}-secret
              key: password
        - name: KUBECONFIG
          value: /app/config/kubeconfig.yaml
        - name: HELM_REPO_NAME
          value: {{ .Values.helmi.repo_name }}
        - name: HELM_REPO_URL
          value: {{ .Values.helmi.repo_url }}
        volumeMounts:
        - mountPath: /app/config
          name: helmi-catalog
        - mountPath: /app/tls
          name: kube-ca
        ports:
        - name: helmi-port
          containerPort: 5000
        livenessProbe:
          httpGet:
            path: /liveness
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 60
        readinessProbe:
          exec:
            command: [ "/bin/sh", "-c", "kubectl version" ]
          initialDelaySeconds: 30
          periodSeconds: 60
      volumes:
      - name: helmi-catalog
        configMap:
          name: {{ template "fullname" . }}-catalog
      - name: kube-ca
        secret:
          secretName: {{ template "fullname" . }}-secret