{{- $serviceName := include "fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}
              servicePort: 5000
    {{- end -}}
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end -}}
---
{{- if .Values.ingress.tls }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: helmi-tls-secret
data:
  tls.crt: {{ .Values.ingress.cert | b64enc }}
  tls.key: {{ .Values.ingress.key | b64enc }}
{{- end }}