apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-secret
type: Opaque
data:
  username: {{ .Values.username | b64enc }}
  password: {{ .Values.password | b64enc }}
  ca.pem: {{ .Values.tls.cacert | b64enc }}